Document: libjson
Title: Debian libjson Manual
Author: <insert document author here>
Abstract: This manual describes what libjson is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libjson/libjson.sgml.gz

Format: postscript
Files: /usr/share/doc/libjson/libjson.ps.gz

Format: text
Files: /usr/share/doc/libjson/libjson.text.gz

Format: HTML
Index: /usr/share/doc/libjson/html/index.html
Files: /usr/share/doc/libjson/html/*.html
